num_updates: 20_000
log_terminal_every: 1000 
run_eval_rollouts: False
log_rollout_videos: False

use_separate_gripper: True
gripper_pos_weight: 0.1

data: 
  data_type: n_step
  seq_len: 5  # chunk size to predict at once
  batch_size: 64

model:
  embedding_model: resnet18
  gaussian_policy: True
  use_separate_gripper: True
  input_modalities: [external_images_embeds,over_shoulder_images_embeds]
  embedder:
    name: hpt

wandb:
  tags:
    - ${data.num_trajs}
    - ${run_id}

defaults:
  - base
  - model/policy@model: ac_transformer
  - _self_