image_extra: im-${.image_obs}_f-${.n_frame_stack} 
hp_name: ${fix_env_hp_name:env_hp, ${.image_obs}, ${.image_extra}}

env_name: null
env_id: null 
dataset_name: null

# number of parallel envs to run during evaluation time
num_envs: 20 
image_obs: null 

# TODO:
gamma: 0.999

# TODO: not used
task_dim: 1
image_shape: null
action_dim: null

n_frame_stack: 1
action_scale: 1

# Only needed for calvin envs. This is optional, if not provided, the data will be loaded as specified in calvin_env.yaml
calvin_data_dir: null